// Package settings - реализует модели данных для хранения настроек сервера и их частичного автозаполнения
package settings

// GetTRulesForGuest - Возвращает заполненный список ролей по всем таблицам будущей базы данных для гостя
func GetTRulesForGuest() SQLTRules {
	return SQLTRules{
		TRule{
			TName:      `"references".files`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".addresses`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".artwork_types`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".authors`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".countries`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".currencies`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".files`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `"references".terms`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},

		TRule{
			TName:      `finance.orders`,
			SELECT:     true,
			INSERT:     true,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: true,
		},
		TRule{
			TName:      `finance.orders_details`,
			SELECT:     true,
			INSERT:     true,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: true,
		},
		TRule{
			TName:      `finance.orders_returns`,
			SELECT:     true,
			INSERT:     true,
			UPDATE:     true,
			DELETE:     true,
			REFERENCES: true,
		},
		TRule{
			TName:      `finance.payments`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `public.artworks`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `secret."users"`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     true,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `secret."hashes"`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     true,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `secret."confirmations"`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `secret."password_resets"`,
			SELECT:     true,
			INSERT:     false,
			UPDATE:     false,
			DELETE:     false,
			REFERENCES: false,
		},
		TRule{
			TName:      `secret."totp"`,
			SELECT:     true,
			INSERT:     true,
			UPDATE:     true,
			DELETE:     true,
			REFERENCES: true,
		},
	}
}
